apiVersion: v1
kind: Service
metadata:
  name: erp-postgres-nodeport
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    nodePort: 32022
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: promerp-development # Only allow for DEV env
    app.kubernetes.io/name: postgresql-erp
  sessionAffinity: None
  type: NodePort
