
erp-api:
  enabled: true
  nameOverride: erp-api

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/erp-service

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        name: http
