erp-api:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"

      - name: IsDev
        value: "false"

      - name: PostgreSQL_Host
        value: "postgresql-erp"

      - name: PostgreSQL_Database
        value: "erp"

      - name: PostgreSQL_User
        value: "postgres"

      - name: PostgreSQL_Password
        valueFrom:
          secretKeyRef:
            name: erp-postgres-secret 
            key: adminPasswordKey
            optional: false
