kong:
  enabled: true
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  dblessConfig:
    configMap: kong-config

  env:
    database: "off"

  customEnv:
    DUMMY: "003" #Update this when Kong configuration is changed in order to restart the pods

  ingressController:
    enabled: false # This is required in DB less mode

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true
