erp-react-ui:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 100Mi

    env:
      - name: HTTP_PORT
        value: "80"

      - name: BASE_URL
        value: "https://sales-api.prom.co.th"

      - name: REACT_APP_BASE_URL
        value: "https://sales-api.prom.co.th"

      - name: REACT_APP_WEB_BASE_URL
        value: "https://sales.prom.co.th"
